export const COUNTRIES = {
  "american samoa": "as",
  "antigua and barbuda": "ag",
  "antigua y barbuda": "ac",
  "arabia saudita": "sa",
  "bosnia and herzegovina": "ba",
  "bosnia y herzegovina": "bk",
  "bouvet island": "bv",
  "british indian ocean territory": "io",
  "brunei darussalam": "bn",
  "brunéi darussalam": "bn",
  "burkina faso": "uv",
  "cabo verde": "cv",
  "cape verde": "cv",
  "cayman islands": "ky",
  "central african republic": "cf",
  "christmas island": "cx",
  "cocos islands": "cc",
  "cook islands": "ck",
  "corea del norte": "kn",
  "costa de marfil": "iv",
  "costa rica": "cs",
  "czech republic": "cz",
  "côte d'ivoire": "ci",
  "democratic republic of the congo": "cd",
  "dominican republic": "do",
  "el salvador": "sv",
  "emiratos árabes unidos": "ae",
  "equatorial guinea": "gq",
  "estados unidos": "us",
  "falkland islands": "fk",
  "faroe islands": "fo",
  "french guiana": "gf",
  "french polynesia": "pf",
  "french southern territories": "tf",
  "guayana francesa": "fr",
  "guinea ecuatorial": "ek",
  "guinea-bissau": "gw",
  "guinea-bisáu": "pu",
  "heard island and mcdonald islands": "hm",
  "hong kong": "hk",
  "isla bouvet": "bv",
  "isla de man": "im",
  "isla de navidad": "kt",
  "isla norfolk": "nf",
  "islas caimán": "cj",
  "islas cocos": "ck",
  "islas cook": "cw",
  "islas falkland": "fk",
  "islas feroe": "fo",
  "islas georgias del sur y sandwich del sur": "sx",
  "islas heard y mcdonald": "hm",
  "islas marianas del norte": "cq",
  "islas marshall": "rm",
  "islas salomón": "bp",
  "islas turcas y caicos": "tk",
  "islas ultramarinas menores de estados unidos": "um",
  "islas virgenes británicas": "vi",
  "islas virgenes de los estados unidos": "vq",
  "islas åland": "fi",
  "keeling islands": "cc",
  "libyan arab jamahiriya": "ly",
  "marshall islands": "mh",
  "netherlands antilles": "an",
  "new caledonia": "nc",
  "new zealand": "nz",
  "norfolk island": "nf",
  "north korea": "kp",
  "northern mariana islands": "mp",
  "nueva caledonia": "nc",
  "nueva zelanda": "nz",
  "papua new guinea": "pg",
  "papúa nueva guinea": "pp",
  "países bajos": "nl",
  "polinesia francesa": "fp",
  "puerto rico": "rq",
  "reino unido": "uk",
  "república centroafricana": "ct",
  "república checa": "ez",
  "república democrática del congo": "cf",
  "república dominicana": "dr",
  "russian federation": "ru",
  "sahara occidental": "wi",
  "saint helena": "sh",
  "saint kitts and nevis": "kn",
  "saint lucia": "lc",
  "saint pierre and miquelon": "pm",
  "saint vincent and the grenadines": "vc",
  "samoa americana": "aq",
  "san bartolomé": "tb",
  "san cristóbal y nieves": "sc",
  "san marino": "sm",
  "san martín": "rn",
  "san pedro y miquelón": "sb",
  "san vicente y las granadinas": "vc",
  "santa helena": "sh",
  "santa lucía": "st",
  "santa sede": "vt",
  "santo tomé y principe": "tp",
  "sao tome and principe": "st",
  "saudi arabia": "sa",
  "sierra leona": "sl",
  "sierra leone": "sl",
  "sint maarten": "sk",
  "solomon islands": "sb",
  "south africa": "za",
  "south georgia and the south sandwich islands": "gs",
  "south korea": "kr",
  "sri lanka": "lk",
  "sudán del sur": "od",
  "svalbard and jan mayen": "sj",
  "svalbard y jan mayen": "sv",
  "syrian arab republic": "sy",
  "territorio británico del océano índico": "io",
  "territorios australes franceses": "fs",
  "timor-leste": "tt",
  "trinidad and tobago": "tt",
  "trinidad y tobago": "td",
  "turks and caicos islands": "tc",
  "united arab emirates": "ae",
  "united kingdom": "gb",
  "united states minor outlying islands": "um",
  "united states of america": "us",
  "united states": "us",
  "viet nam": "vn",
  "virgin islands, british": "vg",
  "virgin islands, u.s.": "vi",
  "wallis and futuna": "wf",
  "wallis y futuna": "wf",
  "western sahara": "eh",
  afganistán: "af",
  afghanistan: "af",
  albania: "al",
  alemania: "gm",
  algeria: "dz",
  andorra: "an",
  angola: "ao",
  anguila: "av",
  antarctica: "aq",
  antártida: "ay",
  argelia: "ag",
  argentina: "ar",
  armenia: "am",
  aruba: "aw",
  australia: "au",
  austria: "au",
  azerbaijan: "az",
  azerbaiyán: "aj",
  bahamas: "bs",
  bahrain: "bh",
  bangladesh: "bd",
  bangladés: "bg",
  barbados: "bb",
  baréin: "ba",
  belarus: "by",
  belgium: "be",
  belice: "bh",
  belize: "bz",
  benin: "bj",
  benín: "bn",
  bermuda: "bm",
  bermudas: "bd",
  bhutan: "bt",
  bielorrusia: "bo",
  bolivia: "bo",
  botsuana: "bc",
  botswana: "bw",
  brasil: "br",
  brazil: "br",
  bulgaria: "bu",
  burundi: "by",
  bután: "bt",
  bélgica: "be",
  cambodia: "kh",
  camboya: "cb",
  cameroon: "cm",
  camerún: "cm",
  canada: "ca",
  canadá: "ca",
  chad: "td",
  chile: "cl",
  china: "cn",
  chipre: "cy",
  colombia: "co",
  comoras: "cn",
  comoros: "km",
  congo: "cg",
  corea: "ks",
  croacia: "hr",
  croatia: "hr",
  cuba: "cu",
  curazao: "cc",
  cyprus: "cy",
  denmark: "dk",
  dinamarca: "da",
  djibouti: "dj",
  dominica: "do",
  ecuador: "ec",
  egipto: "eg",
  egypt: "eg",
  eritrea: "er",
  eslovaquia: "lo",
  eslovenia: "si",
  españa: "sp",
  estonia: "en",
  ethiopia: "et",
  etiopía: "et",
  fiji: "fj",
  filipinas: "rp",
  finland: "fi",
  finlandia: "fi",
  fiyi: "fj",
  france: "fr",
  francia: "fr",
  fyrom: "mk",
  gabon: "ga",
  gabón: "gb",
  gambia: "gm",
  georgia: "gg",
  germany: "de",
  ghana: "gh",
  gibraltar: "gi",
  granada: "gj",
  grecia: "gr",
  greece: "gr",
  greenland: "gl",
  grenada: "gd",
  groenlandia: "gl",
  guadalupe: "fr",
  guadeloupe: "gp",
  guam: "gu",
  guatemala: "gt",
  guernsey: "gk",
  guinea: "gv",
  guyana: "gy",
  haiti: "ht",
  haití: "ha",
  honduras: "ho",
  hungary: "hu",
  hungría: "hu",
  iceland: "is",
  india: "in",
  indonesia: "id",
  irak: "iz",
  iran: "ir",
  iraq: "iq",
  ireland: "ie",
  irlanda: "ei",
  irán: "ir",
  islandia: "ic",
  israel: "is",
  italia: "it",
  italy: "it",
  jamaica: "jm",
  japan: "jp",
  japón: "ja",
  jersey: "je",
  jordan: "jo",
  jordania: "jo",
  kazajistán: "kz",
  kazakhstan: "kz",
  keeling: "ck",
  kenia: "ke",
  kenya: "ke",
  kirguistán: "kg",
  kiribati: "kr",
  korea: "kr",
  kuwait: "kw",
  kyrgyzstan: "kg",
  lao: "la",
  laos: "la",
  latvia: "lv",
  lebanon: "lb",
  lesotho: "ls",
  lesoto: "lt",
  letonia: "lg",
  liberia: "lr",
  libia: "ly",
  liechtenstein: "ls",
  lithuania: "lt",
  lituania: "lh",
  luxembourg: "lu",
  luxemburgo: "lu",
  líbano: "le",
  macao: "mo",
  macedonia: "mk",
  madagascar: "mg",
  malasia: "my",
  malaui: "mi",
  malawi: "mw",
  malaysia: "my",
  maldivas: "mv",
  maldives: "mv",
  mali: "ml",
  malta: "mt",
  malvinas: "fk",
  malí: "ml",
  marruecos: "mo",
  martinica: "fr",
  martinique: "mq",
  mauricio: "mp",
  mauritania: "mr",
  mauritius: "mu",
  mayotte: "yt",
  mexico: "mx",
  micronesia: "fm",
  moldavia: "md",
  moldova: "md",
  monaco: "mc",
  mongolia: "mn",
  montenegro: "mj",
  montserrat: "ms",
  morocco: "ma",
  mozambique: "mz",
  myanmar: "mm",
  méxico: "mx",
  mónaco: "mn",
  nabimia: "wa",
  namibia: "na",
  nauru: "nr",
  nepal: "np",
  netherlands: "nl",
  nicaragua: "nu",
  niger: "ne",
  nigeria: "ni",
  niue: "nu",
  noruega: "no",
  norway: "no",
  níger: "ng",
  oman: "om",
  omán: "mu",
  pakistan: "pk",
  pakistán: "pk",
  palaos: "ps",
  palau: "pw",
  palestina: "gz",
  palestine: "ps",
  panama: "pa",
  panamá: "pm",
  paraguay: "py",
  peru: "pe",
  perú: "pe",
  philippines: "ph",
  pitcairn: "pn",
  poland: "pl",
  polonia: "pl",
  portugal: "pt",
  qatar: "qa",
  rdc: "cd",
  reunión: "fr",
  romania: "ro",
  ruanda: "rw",
  rumania: "ro",
  rusia: "rs",
  rwanda: "rw",
  réunion: "re",
  samoa: "ws",
  scotland: "gb",
  senegal: "sn",
  serbia: "rs",
  seychelles: "se",
  singapore: "sg",
  singapur: "sn",
  siria: "sy",
  slovakia: "sk",
  slovenia: "si",
  somalia: "so",
  spain: "es",
  suazilandia: "wz",
  sudan: "sd",
  sudáfrica: "sf",
  sudán: "su",
  suecia: "sw",
  suiza: "sz",
  surinam: "ns",
  suriname: "sr",
  swaziland: "sz",
  sweden: "se",
  switzerland: "ch",
  tailandia: "th",
  taiwan: "tw",
  taiwán: "tw",
  tajikistan: "tj",
  tanzania: "tz",
  tayikistán: "ti",
  thailand: "th",
  togo: "to",
  tokelau: "tl",
  tonga: "to",
  tunisia: "tn",
  turkey: "tr",
  turkmenistan: "tm",
  turkmenistán: "tx",
  turquía: "tu",
  tuvalu: "tv",
  túnez: "ts",
  ucrania: "up",
  uganda: "ug",
  uk: "gb",
  ukraine: "ua",
  uruguay: "uy",
  us: "us",
  usa: "us",
  uzbekistan: "uz",
  uzbekistán: "uz",
  vanuatu: "vu",
  vaticano: "vt",
  venezuela: "ve",
  vietnam: "vn",
  wales: "gb",
  yemen: "ym",
  yibuti: "dj",
  zambia: "zm",
  zimbabue: "zw",
  zimbabwe: "zw",
};
