import {
  AlbaniaFlag,
  ArmeniaFlag,
  AndorraFlag,
  AngolaFlag,
  ArgentinaFlag,
  AustriaFlag,
  AustraliaFlag,
  BosniaHerzFlag,
  BelgiumFlag,
  BulgariaFlag,
  BruneiFlag,
  BoliviaFlag,
  BrazilFlag,
  CanadaFlag,
  SwitzerlandFlag,
  ChileFlag,
  CameroonFlag,
  ChinaFlag,
  ColombiaFlag,
  CubaFlag,
  CaboVerdeFlag,
  CzechiaFlag,
  GermanyFlag,
  DenmarkFlag,
  AlgeriaFlag,
  EcuadorFlag,
  EstoniaFlag,
  EgyptFlag,
  SpainFlag,
  FinlandFlag,
  FranceFlag,
  GreatBritainFlag,
  GhanaFlag,
  GreenlandFlag,
  GreeceFlag,
  HondurasFlag,
  CroatiaFlag,
  HungaryFlag,
  IrelandFlag,
  IsraelFlag,
  IndiaFlag,
  IcelandFlag,
  ItaliaFlag,
  JamaicaFlag,
  JapanFlag,
  KoreaFlag,
  LebanonFlag,
  LithuaniaFlag,
  LatviaFlag,
  MoroccoFlag,
  MaltaFlag,
  MexicoFlag,
  NigeriaFlag,
  NicaraguaFlag,
  NetherlandsFlag,
  NorwayFlag,
  NewZealandFlag,
  PolandFlag,
  PortugalFlag,
  ParaguayFlag,
  RomaniaFlag,
  SerbiaFlag,
  RussiaFlag,
  SwedenFlag,
  SloveniaFlag,
  SlovakiaFlag,
  ElSalvadorFlag,
  TunisiaFlag,
  TurkeyFlag,
  UkraineFlag,
  UnitedStatesFlag,
  UruguayFlag,
  VenezuelaFlag,
  SouthAfricaFlag,
} from "../assets/images/flags";

const FLAGS = {
  al: AlbaniaFlag,
  am: ArmeniaFlag,
  an: AndorraFlag,
  ao: AngolaFlag,
  ar: ArgentinaFlag,
  at: AustriaFlag,
  au: AustraliaFlag,
  ba: BosniaHerzFlag,
  be: BelgiumFlag,
  bg: BulgariaFlag,
  bn: BruneiFlag,
  bo: BoliviaFlag,
  br: BrazilFlag,
  ca: CanadaFlag,
  ch: SwitzerlandFlag,
  cl: ChileFlag,
  cm: CameroonFlag,
  cn: ChinaFlag,
  co: ColombiaFlag,
  cu: CubaFlag,
  cv: CaboVerdeFlag,
  cz: CzechiaFlag,
  de: GermanyFlag,
  dk: DenmarkFlag,
  dz: AlgeriaFlag,
  ec: EcuadorFlag,
  ee: EstoniaFlag,
  eg: EgyptFlag,
  es: SpainFlag,
  fi: FinlandFlag,
  fr: FranceFlag,
  gb: GreatBritainFlag,
  gh: GhanaFlag,
  gl: GreenlandFlag,
  gr: GreeceFlag,
  hn: HondurasFlag,
  hr: CroatiaFlag,
  hu: HungaryFlag,
  ie: IrelandFlag,
  il: IsraelFlag,
  in: IndiaFlag,
  is: IcelandFlag,
  it: ItaliaFlag,
  jm: JamaicaFlag,
  jp: JapanFlag,
  kr: KoreaFlag,
  lb: LebanonFlag,
  lt: LithuaniaFlag,
  lv: LatviaFlag,
  ma: MoroccoFlag,
  mt: MaltaFlag,
  mx: MexicoFlag,
  ng: NigeriaFlag,
  ni: NicaraguaFlag,
  nl: NetherlandsFlag,
  no: NorwayFlag,
  nz: NewZealandFlag,
  pl: PolandFlag,
  pt: PortugalFlag,
  py: ParaguayFlag,
  ro: RomaniaFlag,
  rs: SerbiaFlag,
  ru: RussiaFlag,
  se: SwedenFlag,
  si: SloveniaFlag,
  sk: SlovakiaFlag,
  sv: ElSalvadorFlag,
  tn: TunisiaFlag,
  tr: TurkeyFlag,
  ua: UkraineFlag,
  us: UnitedStatesFlag,
  uy: UruguayFlag,
  ve: VenezuelaFlag,
  za: SouthAfricaFlag,
};

export const getFlagURL = (countryCode) => FLAGS[countryCode];
