import {
  GK,
  SW,
  RB,
  RCB,
  CB,
  LCB,
  LB,
  RWB,
  LWB,
  RDM,
  CDM,
  LDM,
  RM,
  RCM,
  CM,
  LCM,
  LM,
  RAM,
  CAM,
  LAM,
  RW,
  CF,
  LW,
  RS,
  ST,
  LS,
  GKS,
  DEF,
  MID,
  STR,
  TEC
} from "../constants/positions";

export default {
  en: {
    [GK]: 'Goalkeeper',
    [SW]: 'Sweeper',
    [RB]: 'Right Fullback',
    [RCB]: 'Right Center-back',
    [CB]: 'Center-back',
    [LCB]: 'Left Center-back',
    [LB]: 'Left Fullback',
    [RWB]: 'Right Wing-back',
    [LWB]: 'Left Wing-back',
    [RDM]: 'Right Defensive Mid',
    [CDM]: 'Central Defensive Mid',
    [LDM]: 'Left Defensive Mid',
    [RM]: 'Right Midfielder',
    [RCM]: 'Right Central Mid',
    [CM]: 'Central Midfielder',
    [LCM]: 'Left Central Mid',
    [LM]: 'Left Midfielder',
    [RAM]: 'Right Attacking Mid',
    [CAM]: 'Central Attacking Mid',
    [LAM]: 'Left Attacking Mid',
    [RW]: 'Right Winger',
    [CF]: 'Center Forward',
    [LW]: 'Left Winger',
    [RS]: 'Right Striker',
    [ST]: 'Striker',
    [LS]: 'Left Striker',
    [GKS]: 'Goalkeepers',
    [DEF]: 'Defenders',
    [MID]: 'Midfielders',
    [STR]: 'Strikers',
    [TEC]: 'Technical Staff'
  },
  es: {
    [GK]: 'Portera',
    [SW]: 'Líbera',
    [RB]: 'Lateral derecha',
    [RCB]: 'Defensa derecha',
    [CB]: 'Central',
    [LCB]: 'Defensa izquierda',
    [LB]: 'Lateral izquierda',
    [RWB]: 'Volante derecha',
    [LWB]: 'Volante izquierda',
    [RDM]: 'Volante externa derecha',
    [CDM]: 'Mediocentral',
    [LDM]: 'Volante externa izquierda',
    [RM]: 'Externa derecha',
    [RCM]: 'Medio derecha',
    [CM]: 'Medio central',
    [LCM]: 'Medio izquierda',
    [LM]: 'Externa izquierda',
    [RAM]: 'Medio ofensiva derecha',
    [CAM]: 'Volante de ligación',
    [LAM]: 'Medio ofensiva izquierda',
    [RW]: 'Punta derecha',
    [CF]: 'Punta',
    [LW]: 'Punta izquierda',
    [RS]: 'Extrema derecha',
    [ST]: 'Delantera',
    [LS]: 'Extrema izquierda',
    [GKS]: 'Porteras',
    [DEF]: 'Defensoras',
    [MID]: 'Mediocampistas',
    [STR]: 'Delanteras',
    [TEC]: 'Equipo técnico'
  },
};